issue: issue
issues: issues
Issue: Issue
Issues: Issues
issue_or_issues: "issue(s)"
parent_task: "parent task"
Parent_task: "Parent task"
Parent_tasks: "Parent tasks"
issue_subtask_or_subtasks: "subtask(s)"
issue_subtask: subtask
issue_subtasks: subtasks
issue_Subtask: Subtask
issue_Subtasks: Subtasks
issue_note: note
issue_notes: notes
issue_Note: Note
issue_Notes: Notes
issue_watcher: watcher
issue_watchers: watchers
issue_Watcher: Watcher
issue_Watchers: Watchers
issue_Watched: Watched
issue_watch: watch
Issue_tracking: "Issue tracking"
issue_tracker: tracker
issue_Tracker: Tracker
issue_trackers: trackers
issue_Trackers: Trackers
issue_tracker_or_trackers: "tracker(s)"
issue_Status: Status
issue_status: status
issue_statuses: statuses
issue_assignee: assignee
issue_Assignee: Assignee
issue_Assigned: Assigned
issue_assigned: assigned
issue_assigned_to: "assigned to"
issue_am_assigned_to: "am assigned to"
issue_assignment_to: "assignment to"
issue_priority: priority
issue_Priority: Priority
issue_priorities: priorities
issue_category: category
issue_Category: Category
issue_categories: categories
issue_open: open
issue_Open: Open
issues_open: open
issue_closed: closed
issues_closed: closed
issue_Closed: Closed
project: project
projects: projects
Project: Project
Projects: Projects
subproject: subproject
subprojects: subprojects
Subproject: Subproject
Subprojects: Subprojects
subproject_or_subprojects: "subproject(s)"

test_translation: this is a test translation

