segnalazione: segnalazione
segnalazioni: segnalazioni
Segnalazione: Segnalazione
Segnalazioni: Segnalazioni
sottosegnalazione: sottoattività
sottosegnalazioni: sottoattività
Sottosegnalazioni: Sottoattività
sottosegnalazione_una: "una "
sottosegnalazione_La: "La "
sottosegnalazione_dalle: "dalle "
sottosegnalazione_spostata: spostata
sottosegnalazione_aperta: aperta
segnalazione_Madre: Attività principale
segnalazione_madre: attività principale
segnalazione_campo_Madre: Principale
segnalazione_la: "la "
segnalazione_la_pronome: "la"  # non apostrofato come in 'la stai aggiornando'
segnalazione_La: "La "
segnalazione_le: "le "
segnalazione_una: "una "
segnalazione_Una: "Una "
segnalazione_della: "dell'"
segnalazione_delle: "delle "
segnalazione_sulle: "sulle "
segnalazione_alle: "alle "
segnalazione_una_delle_sue: "una delle sue" # M/F
segnalazione_Le_mie: "Le mie"
segnalazione_questa: "questa"
segnalazione_Alcune: "Alcune"
segnalazione_proprie: proprie
segnalazione_stata_aggiornata: "stata aggiornata"
segnalazione_state_assegnate: "state assegnate"
segnalazione_stata_trovata: "stata trovata"
segnalazione_aperta: aperta
segnalazione_aperte: aperte
segnalazione_riaperta: riaperta
segnalazione_chiusa: chiusa
segnalazione_Chiusa: Chiusa
segnalazione_chiuse: chiuse
segnalazione_Chiudi: Chiudi
segnalazione_chiusura: chiusura
segnalazione_figlia: figlia
segnalazione_mostrate: mostrate
segnalazione_correlate: correlate
segnalazione_completate: completate
segnalazione_pubbliche: pubbliche
segnalazione_Privata: Privata
segnalazione_private: private
segnalazione_relative: relative
segnalazione_nuove: nuove
segnalazione_Nuova: Nuova
segnalazione_tutte: tutte
segnalazione_Tutte: Tutte
segnalazione_selezionate: selezionate
segnalazione_aggiunte: aggiunte
segnalazione_aggiornate: aggiornate
segnalazione_referenziate: referenziate
segnalazione_risolte: risolte
segnalazione_rimossa: rimossa
segnalazione_creata: creata
segnalazione_Creata: Creata
segnalazione_create: create
segnalazione_Aggiornata: Aggiornata
segnalazione_copiate: copiate
segnalazione_duplicate: duplicate
segnalazione_osservate: osservate  # aggettivo
segnalazione_osservi: osservi      # verbo
segnalazione_Osserva: Osserva
segnalazione_osservatore: osservatore
segnalazione_Osservatore: Osservatore
segnalazione_osservatori: osservatori
segnalazione_Osservatori: Osservatori
segnalazione_osservatore_un: "un "
segnalazione_Dimentica: Dimentica
segnalazione_bloccata: bloccata
segnalazione_assegnare: assegnare
segnalazione_assegnata: assegnata
segnalazione_Assegnata: Assegnata
segnalazione_assegnate: assegnate
segnalazione_assegnare: assegnare
segnalazione_assegnatario: assegnatario
segnalazione_Assegnatario: Assegnatario
segnalazione_Assegnatari: Assegnatari
segnalazione_Assegnatario_agg: Assegnatario aggiornato
segnalazione_assegnatario_lo: "l'"
segnalazione_assegn_dello: "dell'"
segnalazione_categoria: categoria
segnalazione_categorie: categorie
segnalazione_Categoria: Categoria
segnalazione_Categorie: Categorie
segnalazione_categoria_la: "la "
segnalazione_categoria_Nuova: Nuova
segnalazione_categoria_questa: questa
segnalazione_stato: stato
segnalazione_stati: stati
segnalazione_Stato: Stato
segnalazione_Stati: Stati
segnalazione_stato_lo: "lo "
segnalazione_stato_questo: questo
segnalazione_stato_Nessuno: Nessuno
segnalazione_stato_Nuovo: Nuovo
segnalazione_stati_Nuovi: Nuovi
segnalazione_stato_applicato: applicato
segnalazione_stato_aggiornato: aggiornato
segnalazione_stato_predefinito: predefinito
segnalazione_stato_configurato: configurato
segnalazione_stato_attivo: attivo
segnalazione_stato_usati: usati
segnalazione_stato_In_elab: "In elaborazione"
segnalazione_stato_Risolto: Risolto
segnalazione_stato_Commenti: Commenti
segnalazione_stato_Chiuso: Chiuso
segnalazione_stato_Rifiutato: Rifiutato
segnalazione_nota: nota
segnalazione_note: note
segnalazione_Nota: Nota
segnalazione_Note: Note
segnalazione_nota_la: "la "
segnalazione_nota_le: "le "
segnalazione_nota_una: "una "
segnalazione_nota_le_mie: "le mie"
segnalazione_nota_aggiunta: aggiunta
segnalazione_nota_salvata: salvata
segnalazione_nota_precedenti: precedenti
segnalazione_nota_mantenute: mantenute
segnalazione_nota_private: private
segnalazione_Tracker: Tracker
segnalazione_tracker: tracker
segnalazione_tracker_plurale: tracker
segnalazione_Tracker_plurale: Tracker
segnalazione_tracker_i: "i "
segnalazione_tracker_dei: "dei"
segnalazione_tracker_Nuovo: Nuovo
segnalazione_tracker_un: "un "
segnalazione_tracker_questo: questo
segnalazione_tracker_Questo: Questo
segnalazione_tracker_nessun: nessun
segnalazione_tracker_Nessun: Nessun
segnalazione_tracker_Tutti: Tutti
segnalazione_tracker_associato: associato
segnalazione_tracker_eliminato: eliminato
segnalazione_tracker_finali: finali
segnalazione_priorita: priorità
segnalazione_Priorita: Priorità
segnalazione_priorita_agg: aggiornata
tempo_Attivita: Attività
diario_Attivita: Attività
progetto: progetto
progetti: progetti
Progetto: Progetto
Progetti: Progetti
progetto_il: "il "
progetto_Il: "Il "
progetto_i: "i "
progetto_I: "I "
progetto_un: "un "
progetto_al: "al "
progetto_ai: "ai"
progetto_dal: "dal"
progetto_dei: "dei "
progetto_del: "del "
progetto_nel: "nel "
progetto_degli: "degli "  # come in 'degli altri progetti'
progetto_allo_stesso: "allo stesso" # maschile/femminile
progetto_ad_uno_dei_miei: "ad uno dei miei"
progetto_i_suoi: "i suoi"
progetto_miei: miei
progetto_tutti: tutti
progetto_Tutti: Tutti
progetto_nuovi: nuovi
progetto_Nuovo: Nuovo
progetto_altri: altri
progetto_Altri: Altri
progetto_nessun: nessun
progetto_questo: questo
progetto_Questo: Questo
progetto_Ultimi: Ultimi
progetto_registrati: registrati
progetto_pubblici: pubblici
progetto_selezionati: selezionati
progetto_visibili: visibili
progetto_chiuso: chiuso
progetto_chiusi: chiusi
progetto_archiviato: archiviato
progetto_attivo: attivo
progetto_padre: padre
progetto_stato: stato  # come in "e' stato"
progetto_privo: privo
progetto_diversi: diversi
progetto_usati: usati
sottoprogetto: sottoprogetto
Sottoprogetto: Sottoprogetto
sottoprogetti: sottoprogetti
Sottoprogetti: Sottoprogetti
ruolo_Gestore: Gestore
ruolo_Sviluppatore: Sviluppatore
ruolo_Segnalatore: Segnalatore

