en-GB:
  activerecord:
    errors:
      messages:
        not_same_project: "doesn't belong to the same %{project}"
        cant_link_an_issue_with_a_descendant: "An %{issue} cannot be linked to one of its %{issue_subtasks}"
        earlier_than_minimum_start_date: "cannot be earlier than %{date} because of preceding %{issues}"
        open_issue_with_closed_parent: "An %{issue_open} %{issue} cannot be attached to a %{issue_closed} %{parent task}"

  notice_not_authorized_archived_project: "The %{project} you're trying to access has been archived."
  notice_failed_to_save_issues: "Failed to save %{count} %{issue_or_issues} on %{total} selected: %{ids}."
  notice_no_issue_selected: "No %{issue} is selected! Please, check the %{issues} you want to edit."
  notice_issue_done_ratios_updated: "%{Issue} done ratios updated."
  notice_issue_successful_create: "%{Issue} %{id} created."
  notice_issue_update_conflict: "The %{issue} has been updated by an other user while you were editing it."

  error_issue_not_found_in_project: 'The %{issue} was not found or does not belong to this %{project}'
  error_no_tracker_in_project: 'No %{issue_tracker} is associated to this %{project}. Please check the %{project} settings.'
  error_no_default_issue_status: 'No default %{issue} %{issue_status} is defined. Please check your configuration (Go to "Administration -> %{Issue} %{issue_statuses}").'
  error_can_not_delete_tracker: "This %{issue_tracker} contains %{issues} and cannot be deleted."
  error_can_not_reopen_issue_on_closed_version: 'An %{issue} assigned to a closed version cannot be reopened'
  error_can_not_archive_project: "This %{project} cannot be archived"
  error_issue_done_ratios_not_updated: "%{Issue} done ratios not updated."
  error_workflow_copy_source: 'Please select a source %{issue_tracker} or role'
  error_workflow_copy_target: 'Please select target %{issue_tracker_or_trackers} and role(s)'
  error_unable_delete_issue_status: 'Unable to delete %{issue} %{issue_status}'
  error_no_tracker_allowed_for_new_issue_in_project: "The %{project} doesn't have any %{issue_trackers} for which you can create an %{issue}"
  error_no_projects_with_tracker_allowed_for_new_issue: "There are no %{projects} with %{issue_trackers} for which you can create an %{issue}"
  error_move_of_child_not_possible: "%{issue_Subtask} %{child} could not be moved to the new %{project}: %{errors}"
  error_cannot_reassign_time_entries_to_an_issue_about_to_be_deleted: "Spent time cannot be reassigned to an %{issue} that is about to be deleted"

  mail_subject_reminder: "%{count} %{issue_or_issues} due in the next %{days} days"
  mail_body_reminder: "%{count} %{issue_or_issues} that are %{issue_assigned_to} you are due in the next %{days} days:"
  field_closed_on: "%{issue_Closed}"
  field_is_for_all: "For all %{projects}"
  field_category: "%{issue_Category}"
  field_project: "%{Project}"
  field_issue: "%{Issue}"
  field_status: "%{issue_Status}"
  field_notes: "%{issue_Notes}"
  field_is_closed: "%{Issue} %{issue_closed}"
  field_tracker: "%{issue_Tracker}"
  field_assigned_to: "%{issue_Assignee}"
  field_priority: "%{issue_Priority}"
  field_parent: "%{Subproject} of"
  field_is_in_roadmap: "%{Issues} displayed in roadmap"
  field_subproject: "%{Subproject}"
  field_issue_to: "Related %{issue}"
  field_assignable: "%{Issues} can be %{issue_assigned_to} this role"
  field_watcher: "%{issue_Watcher}"
  field_parent_issue: "%{Parent_task}"
  field_member_of_group: "%{issue_Assignee}'s group"
  field_assigned_to_role: "%{issue_Assignee}'s role"
  field_issues_visibility: "%{Issues} visibility"
  field_default_status: "Default %{issue_status}"
  field_default_assigned_to: "Default %{issue_assignee}"

  setting_issues_export_limit: "%{Issues} export limit"
  setting_default_projects_public: "New %{projects} are public by default"
  setting_cross_project_issue_relations: "Allow cross-%{project} %{issue} relations"
  setting_cross_project_subtasks: "Allow cross-%{project} %{issue_subtasks}"
  setting_issue_list_default_columns: "Default columns displayed on the %{issue} list"
  setting_display_subprojects_issues: "Display %{subprojects} %{issues} on main %{projects} by default"
  setting_issue_done_ratio: "Calculate the %{issue} done ratio with"
  setting_issue_done_ratio_issue_field: "Use the %{issue} field"
  setting_issue_done_ratio_issue_status: "Use the %{issue} %{issue_status}"
  setting_issue_group_assignment: "Allow %{issue} %{issue_assignment_to} groups"
  setting_default_issue_start_date_to_creation_date: "Use current date as start date for new %{issues}"
  setting_commit_cross_project_ref: "Allow %{issues} of all the other %{projects} to be referenced and fixed"
  setting_default_projects_tracker_ids: "Default %{issue_trackers} for new %{projects}"
  setting_link_copied_issue: "Link %{issues} on copy"
  setting_new_item_menu_tab: "%{Project} menu tab for creating new objects"

  permission_add_project: "Create %{project}"
  permission_add_subprojects: "Create %{subprojects}"
  permission_edit_project: "Edit %{project}"
  permission_close_project: "Close / reopen the %{project}"
  permission_select_project_modules: "Select %{project} modules"
  permission_manage_project_activities: "Manage %{project} activities"
  permission_manage_categories: "Manage %{issue} %{issue_categories}"
  permission_view_issues: "View %{Issues}"
  permission_add_issues: "Add %{issues}"
  permission_edit_issues: "Edit %{issues}"
  permission_copy_issues: "Copy %{issues}"
  permission_manage_issue_relations: "Manage %{issue} relations"
  permission_set_issues_private: "Set %{issues} public or private"
  permission_set_own_issues_private: "Set own %{issues} public or private"
  permission_add_issue_notes: "Add %{issue_notes}"
  permission_edit_issue_notes: "Edit %{issue_notes}"
  permission_edit_own_issue_notes: "Edit own %{issue_notes}"
  permission_view_private_notes: "View private %{issue_notes}"
  permission_set_notes_private: "Set %{issue_notes} as private"
  permission_move_issues: "Move %{issues}"
  permission_delete_issues: "Delete %{issues}"
  permission_view_issue_watchers: "View %{issue_watchers} list"
  permission_add_issue_watchers: "Add %{issue_watchers}"
  permission_delete_issue_watchers: "Delete %{issue_watchers}"
  permission_manage_subtasks: "Manage %{issue_subtasks}"
  permission_manage_related_issues: "Manage related %{issues}"
  permission_import_issues: "Import %{issues}"

  project_module_issue_tracking: "%{Issue_tracking}"

  label_project: "%{Project}"
  label_project_new: "New %{project}"
  label_project_plural: "%{Projects}"
  label_x_projects:
    zero: "no %{projects}"
    one: "1 %{project}"
    other: "%{count} %{projects}"
  label_project_all: "All %{Projects}"
  label_project_latest: "Latest %{projects}"
  label_issue: "%{Issue}"
  label_issue_new: "New %{issue}"
  label_issue_plural: "%{Issues}"
  label_issue_view_all: "View all %{issues}"
  label_issues_by: "%{Issues} by %{value}"
  label_issue_added: "%{Issue} added"
  label_issue_updated: "%{Issue} updated"
  label_issue_note_added: "%{issue_Note} added"
  label_issue_status_updated: "%{issue_Status} updated"
  label_issue_assigned_to_updated: "%{issue_Assignee} updated"
  label_issue_priority_updated: "%{issue_Priority} updated"
  label_tracker: "%{issue_Tracker}"
  label_tracker_plural: "%{issue_Trackers}"
  label_tracker_all: "All %{issue_trackers}"
  label_tracker_new: "New %{issue_tracker}"
  label_issue_status: "%{Issue} %{issue_status}"
  label_issue_status_plural: "%{Issue} %{issue_statuses}"
  label_issue_status_new: "New %{issue_status}"
  label_issue_category: "%{Issue} %{issue_category}"
  label_issue_category_plural: "%{Issue} %{issue_categories}"
  label_issue_category_new: "New %{issue_category}"
  label_my_projects: "My %{projects}"
  label_reported_issues: "Reported %{issues}"
  label_assigned_issues: "%{issues_Assigned} %{issues}"
  label_assigned_to_me_issues: "%{Issues} %{issue_assigned_to} me"
  label_subproject_plural: "%{Subprojects}"
  label_subproject_new: "New %{subproject}"
  label_and_its_subprojects: "%{value} and its %{subprojects}"
  label_change_status: "Change %{issue_status}"
  label_public_projects: "Public %{projects}"
  label_open_issues: "%{issue_open}"
  label_open_issues_plural: "%{issues_open}"
  label_closed_issues: "%{issue_closed}"
  label_closed_issues_plural: "%{issue_closed}"
  label_x_open_issues_abbr:
    zero: "0 %{issues_open}"
    one: "1 %{issue_open}"
    other: "%{count} %{issues_open}"
  label_x_closed_issues_abbr:
    zero: "0 %{issues_closed}"
    one: "1 %{issue_closed}"
    other: "%{count} %{issues_closed}"
  label_x_issues:
    zero: "0 %{issues}"
    one: "1 %{issue}"
    other: "%{count} %{issues}"
  label_current_status: "Current %{issue_status}"
  label_new_statuses_allowed: "New %{issue_statuses} allowed"
  label_add_note: "Add a %{issue_note}"
  label_any_issues_in_project: "any %{issues} in %{project}"
  label_any_issues_not_in_project: "any %{issues} not in %{project}"
  label_no_issues_in_project: "no %{issues} in %{project}"
  label_any_open_issues: "any open %{issues}"
  label_no_open_issues: "no open %{issues}"
  label_roadmap_no_issues: "No %{issues} for this version"
  label_issue_tracking: "%{Issue_tracking}"
  label_watched_issues: "%{issue_Watched} %{issues}"
  label_related_issues: "Related %{issues}"
  label_applied_status: "Applied %{issue_status}"
  label_jump_to_a_project: "Jump to a %{project}..."
  label_bulk_edit_selected_issues: "Bulk edit selected %{issues}"
  label_user_mail_option_all: "For any event on all my %{projects}"
  label_user_mail_option_selected: "For any event on the selected %{projects} only..."
  label_user_mail_option_only_my_events: "Only for things I %{issue_watch} or I'm involved in"
  label_user_mail_option_only_assigned: "Only for things I %{issue_watch} or I %{issue_am_assigned_to}"
  label_user_mail_option_only_owner: "Only for things I %{issue_watch} or I am the owner of"
  label_issue_watchers: "%{issue_Watchers}"
  label_version_sharing_descendants: "With %{subprojects}"
  label_version_sharing_hierarchy: "With %{project} hierarchy"
  label_version_sharing_tree: "With %{project} tree"
  label_version_sharing_system: "With all %{projects}"
  label_update_issue_done_ratios: "Update %{issue} done ratios"
  label_display_used_statuses_only: "Only display %{issue_statuses} that are used by this %{issue_tracker}"
  label_subtask_plural: "%{issue_Subtasks}"
  label_project_copy_notifications: "Send email notifications during the %{project} copy"
  label_additional_workflow_transitions_for_assignee: "Additional transitions allowed when the user is the %{issue_assignee}"
  label_issues_visibility_all: "All %{issues}"
  label_issues_visibility_public: "All non private %{issues}"
  label_issues_visibility_own: "%{Issues} created by or %{issue_assigned_to} the user"
  label_copy_subtasks: "Copy %{issue_subtasks}"
  label_search_for_watchers: "Search for %{issue_watchers} to add"
  label_show_closed_projects: "View closed %{projects}"
  label_status_transitions: "%{issue_Status} transitions"
  label_attribute_of_project: "%{Project}'s %{name}"
  label_attribute_of_issue: "%{Issue}'s %{name}"
  label_attribute_of_assigned_to: "%{issue_Assignee}'s %{name}"
  label_cross_project_descendants: "With %{subprojects}"
  label_cross_project_tree: "With %{project} tree"
  label_cross_project_hierarchy: "With %{project} hierarchy"
  label_cross_project_system: "With all %{projects}"
  label_add_projects: "Add %{projects}"
  label_users_visibility_members_of_visible_projects: "Members of visible %{projects}"
  label_link_copied_issue: "Link copied %{issue}"
  label_search_open_issues_only: "%{issue_Open} %{issues} only"
  label_parent_task_attributes: "%{Parent_tasks} attributes"
  label_parent_task_attributes_derived: "Calculated from %{issue_subtasks}"
  label_parent_task_attributes_independent: "Independent of %{issue_subtasks}"
  label_import_issues: "Import %{issues}"
  label_new_project_issue_tab_enabled: 'Display the "New %{issue}" tab'
  label_last_notes: "Last %{issue_notes}"

  text_project_destroy_confirmation: "Are you sure you want to delete this %{project} and related data?"
  text_subprojects_destroy_warning: "Its %{subproject_or_subprojects}: %{value} will be also deleted."
  text_workflow_edit: "Select a role and a %{issue_tracker} to edit the workflow"
  text_tip_issue_begin_day: "%{issue} beginning this day"
  text_tip_issue_end_day: "%{issue} ending this day"
  text_tip_issue_begin_end_day: "%{issue} beginning and ending this day"
  text_tracker_no_workflow: "No workflow defined for this %{issue_tracker}"
  text_issues_ref_in_commit_messages: "Referencing and fixing %{issues} in commit messages"
  text_issue_added: "%{Issue} %{id} has been reported by %{author}."
  text_issue_updated: "%{Issue} %{id} has been updated by %{author}."
  text_issue_category_destroy_question: "Some %{issues} (%{count}) are %{issue_assigned_to} this %{issue_category}. What do you want to do?"
  text_issue_category_destroy_assignments: "Remove %{issue_category} assignments"
  text_issue_category_reassign_to: "Reassign %{issues} to this %{issue_category}"
  text_user_mail_option: "For unselected %{projects}, you will only receive notifications about things you %{issue_watch} or you're involved in (eg. %{issues} you're the author or %{issue_assignee})."
  text_no_configuration_data: "Roles, %{issue_trackers}, %{issue} %{issue_statuses} and workflow have not been configured yet.\nIt is highly recommended to load the default configuration. You will be able to modify it once loaded."
  text_issues_destroy_confirmation: 'Are you sure you want to delete the selected %{issue_or_issues}?'
  text_issues_destroy_descendants_confirmation: "This will also delete %{count} %{issue_subtask_or_subtasks}."
  text_select_project_modules: 'Select modules to enable for this %{project}:'
  text_destroy_time_entries_question: "%{hours} hours were reported on the %{issues} you are about to delete. What do you want to do?"
  text_assign_time_entries_to_project: "Assign reported hours to the %{project}"
  text_reassign_time_entries: 'Reassign reported hours to this %{issue}:'
  text_issue_conflict_resolution_overwrite: "Apply my changes anyway (previous %{issue_notes} will be kept but some changes may be overwritten)"
  text_issue_conflict_resolution_add_notes: "Add my %{issue_notes} and discard my other changes"
  text_project_closed: "This %{project} is closed and read-only."

  enumeration_issue_priorities: "%{Issue} %{issue_priorities}"
  description_choose_project: "%{Projects}"
  description_notes: "%{issue_Notes}"
  description_issue_category_reassign: "Choose %{issue} %{issue_category}"
